### ISSUE TITLE
Mirror API request format from the frontend in the API

### ISSUE THREAD

**Issue by ghost** [csc4008-project/api#1]
This is a summary of the current state of API requests on the frontend.

---

Endpoint `/login`

The frontend will send a request in this format:

```
{
  'email': ...,
  'password': ...
}
```

It expects the following response:

```
{
  'accessToken': ...,
  'email': ...,
  'name': ...
}
```

The user details are committed to local storage and used to render some parts of the UI (for example, the `Hello <Name>` text in the navbar and to display the user's current details on the profile page.

The access token will be sent in all authenticated API requests using the `Authorization: Bearer xxx` header.

---

Endpoint `/register`

The frontend will send a request in this format:

```
{
  'name': ...,
  'email': ...,
  'password': ...
}
```

It expects the following response:

```
{
  'accessToken': ...,
  'email': ...,
  'name': ...
}
```

---

Endpoint `/updateAccount`

```
{
  'name': ...,
  'email': ...,
  'password': ...
}
```

(The `Authorization` header will be set for this request.)

**The password may be empty which indicates the user did not want to change their password.**  We might want to discuss not sending this in this case.

It expects the following response:

```
{
  'accessToken': ...,
  'email': ...,
  'name': ...,
}
```

This means the server will repeat back to the frontend the details.  These are committed to local storage in the same way as the login page.

**Comment by jandrews20** [comment]
API Endpoints for Login and Update Account are now mirrored with dummy data and real JWT tokens.
Meaning we can verify that authorization will work. Waiting for database integration for full implementation.

**Comment by jandrews20** [comment]
API Endpoints fully integrated.
Awaiting testing and then issue can be closed.

**Comment by jandrews20** [comment]
Login API tested and functional
