### ISSUE TITLE
Discuss Necessary Booking Endpoints and Implement

### ISSUE THREAD

**Issue by jandrews20** [csc4008-project/api#3]
A meeting will have to take place where we discuss what endpoints are needed for booking, what database queries we will need and what kind of errors and data we expect to be returned from the endpoints.

**Comment by ghost** [comment]
`/listBookings`

This endpoint returns a list of bookings which the user is **either** and attendee on or has created.

Authenticated: Yes

Request: No additional request data

Response codes:

200 OK
401 Unauthorized

Response example:

```
{
    bookings: {
        --booking_id--: {
            --booking_model--
        },
        --booking_id--: {
            --booking_model--
        }
    }
}
```

`/deleteBooking`

Given a booking ID, this endpoint will cancel the meeting **if the sender has permissions to cancel** (i.e. they own the meeting).

Request:

```
{
    booking_id

```

Response codes:

- 200 OK
- 401 Unauthorized

Response: None

`/findBuildings`

Authenticated: Yes

Request: No additional request data

Response codes:

- 200 OK
- 401 Unauthorized

Response:

```
{
    buildings: {
        --building_id--: {
            --building_model--
        },
        --building_id--: {
            --building_model--
        }
    }
}
```

`/findFloors`

Given a building ID, this endpoints returns a list of floors within the building.

Authenticated: Yes

Request:

```
{
    building_id: --building_id--
}
```

Response codes:

- 200 OK
- 401 Unauthorized

Response:

```
{
    floors: {
        --floor_id--: {
            --floor_model--
        },
        --floor_id--: {
            --floor_model--
        }
    }
}
```

`/listSpaces`

Given a floor ID, this endpoint returns all the spaces within it for desk bookings.

Authenticated: Yes

Request:

```
{
    space_id: --space_id--
}
```

Response codes:

- 200 OK
- 401 Unauthorized

Response:

```
{
    spaces: {
        --space_id--: {
            --space_model--
        },
        --space_id--: {
            --space_model--
        }
    }
}
```

`/listRooms`

Given a floor ID, this endpoint returns all the rooms within it for room bookings.

Authenticated: Yes

Request:

```
{
    room_id: --room_id--
}
```

Response codes:

- 200 OK
- 401 Unauthorized

Response:

```
{
    rooms: {
        --room_id--: {
            --room_model--
        },
        --room_id--: {
            --room_model--
        }
    }
}
```

`/createBooking`

Given the details of a booking and either a space ID or room ID, this endpoint will create either a room or desk booking.

Authenticated: Yes

Request:

```
{
    space_id?: --space_id--,
    room_id?: --space_id--,
    attendees: [ --attendee_id--, --attendee_id--, --attendee_id-- ],
    start: --start_datetime_iso_8601--,
    duration: --duration_in_hours--
}
```

Response codes:

- 200 OK
- 400 Bad Request (existing booking at date and time)
- 401 Unauthorized

Response:

```
{
    message: --message--
}
```

__The given message will be displayed to the user.__

**Comment by ghost** [comment]
`/listDesks`

Given a space ID, this endpoints returns a list of desks within the space.

Authenticated: Yes

Request:

```
{
    space_id: --space_id--
}
```

Response codes:

- 200 OK
- 401 Unauthorized

Response:

```
{
    desks: {
        --desk_id--: {
            --desk_model--
        },
        --desk_id--: {
            --desk_model--
        },
    }
}
```

---

`/listEmployees`

This endpoints returns a list of employees within the system.

Authenticated: Yes

Request: None

Response codes:

- 200 OK
- 401 Unauthorized

Response:

```
{
    employees: {
        --employee_id--: {
            --employee_model--
        },
        --employee_id--: {
            --employee_model--
        },
    }
}
```

**Comment by jandrews20** [comment]
Additional endpoints added to facilitate updating bookings (/changeAttendees)
